#
# Additional configuration options for e-paper display support
#

CONFIG_DISPLAY=y
CONFIG_SPI=y
CONFIG_SSD16XX=y
CONFIG_CHARACTER_FRAMEBUFFER=y

# Required for printing floats (%.1f)
CONFIG_CBPRINTF_FP_SUPPORT=y
